pipeline {
    agent any
    stages{
        
   
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivered"
            }
        }
        stage('Complete'){
            steps{
                echo "Job complete"
            }
        }
    }
    }

